export const evenDayCustomers = [
  "BHX - 376 Lý Thái Tổ, Ấp Bến Sắn",
  "BHX - Tổ 31 Ấp Trầu, Phước Thiền",
  "BHX - Thửa 67 Phước Thiền - 8108",
  "BHX - Ấp Trầu (Phước Thiền) Gia Dụng - 6776",
  "BHX: Tổ 25, Ấp Bến Sắn, Phước Thiền",
  "BHX: ẤP 5 Tam An, Long Thành 7011",
  "Vinmart+ - DNI 55/7 Phạm Văn Đồng - 6187",
  "Concung - 450 Lý Thái Tổ ( Vòng Xoay Bến Cam) - 507",
  "Concung - 55/7 Phạm Văn Đồng - 891",
  "Concung - Hương Lộ 21 - 1156",
  "CÔNG TY TNHH PHAN BÁ LỘC - Nhơn Trạch, Đồng Nai",
  "Công ty PV GAS D- Nhơn Trạch",
  "Suất ăn công nghiệp Gô Co Vi Na (Bếp Ansell Vina, Long Thành)",
  "SACN Hưng Thịnh (Bếp công ty Cadivi)",
  "SACN Hưng Thịnh (Bếp công ty Welcron Global)",
  "SACN TUẤN PHÁT (Công ty Lotte Chemical Việt Nam, Nhơn Trạch)",
  "Suất ăn công nghiệp Bizen (Bếp OM Digital, Long Thành)",
  "Hai Đô",
  "Hoàng Ân",
  "Châu Lan",
  "Hùng Quỳnh",
  "Năm Biên",
  "Anh Thy",
  "Thảo Linh",
  "TRƯỜNG MẦM NON BÌNH MINH",
  "Vinh Quang 1",
  "Bảo Ngọc",
  "Bà Phương",
  "Bh Hồng Gấm",
  "Hoàng Hiệp",
  "Linh Trường"
];

export const oddDayCustomers = [
  "BHX - 620H, đường Lê Duẩn, Tổ 1, Cầu Xéo, Long Thành",
  "BHX - Tổ 10, Ấp 1, Xã Long Thọ",
  "BHX - Tổ 9, Ấp 3, Hiệp Phước",
  "BHX - Phú Hội, Nhơn Trạch - 8913",
  "BHX - Thửa 219 Phú Thạnh - 6818",
  "BHX - Vĩnh Tuy (Long Tân), Nhơn Trạch - 6256",
  "Concung - 771 Hùng Vương - 794",
  "Concung - 292 Hùng Vương - 816",
  "MẪU GIÁO ĐỘC LẬP THÙY DƯƠNG",
  "Trường MN Độc Lập Thế Giới Mới, Long Thành",
  "TRƯỜNG MẦM NON DÂN LẬP SAO MAI",
  "Suất ăn công nghiệp Hoa Mai (Bếp Olympus, Long Thành)",
  "Suất ăn công nghiệp CJ (Bếp Joowon, Nhơn Trạch, Đồng Nai)",
  "CÔNG TY TNHH PHAN BÁ LỘC - Nhơn Trạch, Đồng Nai",
  "Suất ăn công nghiệp Hoa Mai (Bếp ODSV (OM), Long Thành)",
  "Suất ăn công nghiệp CJ (Bếp Công Nghiệp T.A VN, Nhơn Trạch, Đồng Nai)",
  "Suất ăn công nghiệp CJ (Bếp Công Ty A&E, Nhơn Trạch, Đồng Nai)",
  "FamilyMart SWANBAY, Nhơn Trạch, Đồng Nai - 00281",
  "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ MINH DŨNG CƯỜNG",
  "Hoàng Oanh",
  "Bối Bối",
  "Cô Hồng",
  "Cô Đen",
  "Kim Tuyến",
  "Mỹ Dung",
  "Bhg Long Tân",
  "Ngọc Mến",
  "Xuân Thảo",
  "Ngọc Dung",
  "Triệu Mẫn",
  "Khánh Linh",
  "Hai Thuận",
  "Thanh Tiền"
];
